version: "3"
services:
  reco-core:
    build: .
    image: reco-core:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      JDBC_DRIVER: "com.mysql.cj.jdbc.Driver"
      JDBC_URL: "jdbc:mysql://db:3306/mydb?useSSL=false"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    volumes:
      - reco-core-volume:/var/lib/mysql

volumes:
  reco-core-volume:
